import {client,userId} from './supabase';import {parseRecord,recordKey,validDate,parseBackup} from './validation';
export type SavedRecord=Record<string,any>&{key:string;revision:number};
const conflict='Este registro cambió en otro dispositivo. Actualizá, revisá la versión más reciente y volvé a editar. Tus cambios no se sobrescribieron.';
export async function loadRecords():Promise<SavedRecord[]>{const owner=await userId();const all:SavedRecord[]=[];for(let from=0;from<10000;from+=500){const {data,error}=await client().from('fuerza_records').select('key,payload,revision').eq('owner_id',owner).order('key').range(from,from+499);if(error)throw Error('No se pudieron cargar los registros. Revisá la conexión y reintentá.');all.push(...data.map(r=>({...r.payload,key:r.key,revision:r.revision})));if(data.length<500)break;}return all;}
export async function saveRecord(type:string,input:unknown,expected?:number){const record=parseRecord(type,input),key=recordKey(record),owner=await userId();let response;
if(expected===undefined){response=await client().from('fuerza_records').insert({owner_id:owner,key,payload:record}).select('revision').single();}
else{response=await client().from('fuerza_records').update({payload:record}).eq('owner_id',owner).eq('key',key).eq('revision',expected).select('revision').maybeSingle();}
if(response.error?.code==='23505'||(!response.error&&!response.data))throw Error(conflict);
if(response.error||!response.data)throw Error('No se guardó. Revisá tu conexión y reintentá.');return {key,revision:response.data.revision};}
export async function uploadPhoto(file:File,date:string,expected?:number){validDate.parse(date);if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024||file.size===0)throw Error('Usá una imagen JPG, PNG o WebP de hasta 5 MB.');
const bytes=new Uint8Array(await file.slice(0,12).arrayBuffer());const valid=file.type==='image/jpeg'?bytes[0]===255&&bytes[1]===216:file.type==='image/png'?bytes[0]===137&&bytes[1]===80:bytes[0]===82&&bytes[8]===87;if(!valid)throw Error('La imagen no es válida.');
const owner=await userId(),ext=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':'webp',path=owner+'/'+date+'/'+crypto.randomUUID()+'.'+ext;const {error}=await client().storage.from('fuerza-photos').upload(path,file,{contentType:file.type,upsert:false});if(error)throw Error('No se pudo subir la foto. Revisá la conexión y el límite de almacenamiento.');try{await saveRecord('photo',{date,path},expected);}catch(e){await client().storage.from('fuerza-photos').remove([path]);throw e;}return path;}
export async function downloadPhoto(path:string){const owner=await userId();if(!path.startsWith(owner+'/'))throw Error('Foto no autorizada');const {data,error}=await client().storage.from('fuerza-photos').download(path);if(error)throw Error('No se pudo cargar esta foto.');return data;}
export async function importBackup(input:unknown,existing:SavedRecord[]){const rows=parseBackup(input),keys=new Set(existing.map(r=>r.key));if(rows.some(r=>keys.has(recordKey(r))))throw Error('Hay fechas o configuración ya existentes. Para evitar sobrescribir datos, importá solo registros nuevos.');const owner=await userId();const batch=rows.map(r=>({owner_id:owner,key:recordKey(r),payload:r}));if(!batch.length)throw Error('El respaldo no contiene registros importables.');const {error}=await client().from('fuerza_records').insert(batch);if(error)throw Error('No se importó: revisá la conexión o si otro dispositivo agregó los mismos datos.');return batch.length;}
