export const initialProfile={start:new Date().toISOString().slice(0,10),calories:2600,sex:'unknown',baselineSteps:5000,notes:'',lastAdjustment:'',age:null as number|null,height:null as number|null,initialWeight:null as number|null,goalWeight:null as number|null};
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function offset(date:string,n:number){return new Date(Date.parse(date+'T12:00:00Z')+n*864e5).toISOString().slice(0,10)}
export function dayOf(start:string,date=today()){return Math.floor((Date.parse(date)-Date.parse(start))/864e5)+1}
export function mean(a:any[],field:string){const ns=a.map(x=>x[field]).filter(x=>typeof x==='number');return ns.length?ns.reduce((a,b)=>a+b,0)/ns.length:null}
export function review(logs:any[],profile:any,at=today()){
const window=(a:number,b:number)=>logs.filter(x=>x.date>=offset(at,a)&&x.date<=offset(at,b));
const a=window(-6,0),b=window(-13,-7),c=window(-20,-14);const n=(r:any[])=>r.filter(x=>typeof x.weight==='number').length;
const current=mean(a,'weight'),prior=mean(b,'weight'),older=mean(c,'weight');
const loss=current!==null&&prior!==null?prior-current:null;
const adherence=a.filter(x=>typeof x.calories==='number'&&Math.abs(x.calories-profile.calories)<=150&&x.protein>=180).length/7;
const waistRecent=[...a].filter(x=>x.waist!=null).sort((x,y)=>x.date.localeCompare(y.date)).at(-1)?.waist;
const waistOld=[...b,...c].filter(x=>x.waist!=null).sort((x,y)=>x.date.localeCompare(y.date))[0]?.waist;
let title='Primero, reunir datos',message='Registrá al menos 4 pesos por semana durante 2 semanas completas. No ajustes por un día aislado.',delta=0;
if(n(a)>=4&&n(b)>=4){title='Mantené el rumbo';message='Mantené calorías y observá otra semana. Buscamos aproximadamente 0,4–0,9 kg por semana con buena recuperación.';
if((mean(a,'energy')??5)<=2||(mean(a,'sleep')??8)<6||(mean(a,'hunger')??1)>=4){title='Priorizá la recuperación';message='No recortes. Revisá sueño, hambre y rendimiento. Considerá 150 kcal más y reducir 30–40 % las series durante una semana; si persiste, consultá.';delta=150;}
else if(loss!==null&&loss>current!*.01){title='El descenso puede ser demasiado rápido';message='Si ya pasaron las primeras 2 semanas, sumá 150 kcal y revisá fuerza y energía. Al inicio puede ser agua; no compenses recortando más.';delta=dayOf(profile.start,at)>14?150:0;}
else if(n(c)>=4&&loss!==null&&loss<.25&&older!-prior!<.25){if(adherence<.8){title='Mejorá la constancia antes de recortar';message='No hay suficientes días dentro del objetivo. Revisá porciones, aceite, fines de semana y registros faltantes.';}else if(waistRecent==null||waistOld==null){title='Sumá una medida de cintura';message='Antes de recortar por un estancamiento, compará cintura con la de hace 2–3 semanas.';}else if(waistRecent<waistOld-.5){title='La cintura está bajando';message='Mantené calorías: puede haber pérdida de grasa aunque el peso cambie poco.';}else {title='Probá un ajuste pequeño';message='Con 2 semanas sin descenso y buena adherencia, reducí 100–150 kcal O sumá 1000 pasos diarios. Elegí solo uno y evaluá en 14 días.';delta=-150;}}}
if(profile.calories+delta<2000){delta=0;message+=' No bajar automáticamente de 2000 kcal; revisá el caso con un nutricionista.';}
if(profile.lastAdjustment && dayOf(profile.lastAdjustment,at)<=14 && delta!==0){delta=0;title='Dale tiempo al último ajuste';message='Esperá 14 días desde el último cambio antes de otro ajuste rutinario. Si hay hambre intensa, fatiga o descenso rápido, revisá antes con un profesional; no sigas recortando.';} if(profile.lastAdjustment===at || profile.calories+delta>3500){delta=0;} return {current,prior,loss,adherence,title,message,delta,count:a.length};}
export const foods:any={avena:['Avena seca',389,17,66,7],leche:['Leche descremada (ml)',35,3.4,5,.1],huevo:['Huevo sin cáscara',143,12.6,.7,9.5],banana:['Banana pelada',89,1.1,23,.3],pollo:['Pollo cocido sin piel',165,31,0,3.6],lenteja:['Lentejas cocidas',116,9,20,.4],poroto:['Porotos cocidos',127,8.7,23,.5],garbanzo:['Garbanzos cocidos',164,8.9,27.4,2.6],verdura:['Verduras variadas',30,1.5,5,.3],aceite:['Aceite',900,0,0,100],yogur:['Yogur natural alto en proteína',60,10,4,.5],manzana:['Manzana',52,.3,14,.2],maiz:['Maíz cocido',96,3.4,21,1.5],pan:['Pan integral',250,9,43,4],arroz:['Arroz cocido',130,2.7,28,.3],atun:['Atún al natural escurrido',116,26,0,1],papa:['Papa hervida',87,1.9,20,.1],queso:['Queso fresco magro',160,24,4,5],mani:['Maní sin sal',567,26,16,49]};
export type Meal={name:string;items:[string,number][];tip:string};
export const menus:Meal[][]=[
[{name:'Desayuno · avena y huevos',items:[['avena',40],['leche',250],['huevo',100],['banana',100]],tip:'Avena con leche y 2 huevos aparte. Prepará la avena la noche anterior.'},{name:'Almuerzo · lentejas con pollo',items:[['pollo',150],['lenteja',150],['verdura',250],['aceite',10]],tip:'Guiso con zapallo, zanahoria y cebolla; aceite medido al servir.'},{name:'Merienda · yogur y fruta',items:[['yogur',250],['manzana',150],['pan',30]],tip:'Elegí un yogur con unos 10 g de proteína por 100 g; revisá etiqueta.'},{name:'Cena · ensalada tibia',items:[['pollo',150],['garbanzo',100],['maiz',80],['verdura',250],['aceite',10]],tip:'Garbanzos, choclo, pollo y verduras. Limón y especias a gusto.'}],
[{name:'Desayuno · tostadas completas',items:[['pan',60],['huevo',100],['queso',60],['manzana',150]],tip:'2 huevos y queso magro con tostadas; fruta entera.'},{name:'Almuerzo · porotos y arroz',items:[['poroto',150],['arroz',100],['pollo',130],['verdura',250],['aceite',5]],tip:'Cociná porotos por tandas y congelá porciones.'},{name:'Merienda · yogur con avena',items:[['yogur',300],['avena',30],['banana',100]],tip:'Una opción práctica 1–2 horas antes de entrenar si la tolerás.'},{name:'Cena · pollo con papas',items:[['pollo',150],['papa',150],['verdura',250],['aceite',10]],tip:'Horno o plancha. Sumá especias y ensalada de estación.'}],
[{name:'Desayuno · avena cremosa',items:[['avena',50],['yogur',250],['banana',100],['mani',10]],tip:'El maní se pesa: es nutritivo, pero concentrado en energía.'},{name:'Almuerzo · garbanzos y atún',items:[['garbanzo',150],['atun',120],['verdura',250],['aceite',10],['pan',30]],tip:'Podés usar pollo cocido en lugar de atún; las macros cambian.'},{name:'Merienda · leche y tostada',items:[['leche',300],['pan',40],['queso',80]],tip:'Una merienda sin necesidad de suplementos.'},{name:'Cena · lentejas y pollo',items:[['lenteja',150],['pollo',150],['verdura',250],['aceite',5]],tip:'Aumentá las legumbres gradualmente si hoy comés poca fibra.'}]
];
export function nutrition(items:[string,number][]){return items.reduce((sum,item)=>sum.map((v,i)=>v+foods[item[0]][i+1]*item[1]/100),[0,0,0,0]);}
export const extra:Meal={name:'Complemento para acercarte a 2600 kcal',items:[['arroz',200],['banana',120],['aceite',10],['pan',60]],tip:'Distribuí estos alimentos entre almuerzo, preentreno y cena; no es una comida adicional obligatoria.'};
export const sessions=[
{name:'Torso A',day:'Lunes',ex:[['Press banca','3','5–8','2–3 min','Pies firmes, escápulas estables.','Press con mancuernas'],['Remo con apoyo de pecho','3','6–10','2 min','No tires con la zona lumbar.','Remo en máquina'],['Jalón al pecho','3','8–12','2 min','Bajá los codos sin balancearte.','Dominada asistida'],['Press de hombros sentado','2','8–10','2 min','No arquees de más la espalda.','Press en máquina'],['Elevación lateral','2','12–15','60–90 s','Controlá el descenso.','Elevación en polea'],['Tríceps en polea','2','10–15','60–90 s','Codos estables.','Extensión con mancuerna']]},
{name:'Pierna A',day:'Martes',ex:[['Sentadilla','3','5–8','3 min','Profundidad que controles sin dolor.','Prensa'],['Peso muerto rumano','3','6–10','2–3 min','Cadera atrás, barra cerca, espalda estable.','Bisagra con mancuernas'],['Curl femoral','2','10–15','90 s','Sin despegar la cadera.','Curl sentado'],['Gemelos','3','10–15','60–90 s','Recorrido completo y pausado.','Gemelos sentado'],['Plancha','2','20–40 s','60 s','Respirá sin perder la postura.','Dead bug']]},
{name:'Torso B',day:'Jueves',ex:[['Press inclinado con mancuernas','3','6–10','2–3 min','Controlá la bajada.','Press inclinado en máquina'],['Jalón neutro','3','8–12','2 min','Sin impulso.','Dominada asistida'],['Remo en polea','3','8–12','2 min','Torso estable.','Remo con apoyo'],['Elevación lateral','2','12–15','60–90 s','No encojas los hombros.','Polea lateral'],['Curl bíceps','2','10–15','60–90 s','Sin balanceo.','Curl en polea'],['Tríceps en polea','2','10–15','60–90 s','Recorrido cómodo.','Extensión en máquina']]},
{name:'Pierna B',day:'Viernes',ex:[['Prensa','3','8–12','2–3 min','No despegues la pelvis del respaldo.','Sentadilla goblet'],['Hip thrust','3','8–12','2 min','Terminá con glúteos, sin hiperextender.','Puente de glúteos'],['Curl femoral','3','10–15','90 s','Controlá ambas fases.','Curl acostado'],['Extensión de cuádriceps','2','10–15','90 s','Sin rebotes y sin dolor.','Zancada asistida'],['Gemelos','2','10–15','60–90 s','Pausa arriba y abajo.','Gemelos en prensa'],['Dead bug','2','8–12/lado','60 s','Zona lumbar estable.','Plancha']]}
];
export const weeks=[
['Construir la base','Pesá porciones durante unos días. Reducí frituras y medí el aceite. Conservá una porción planificada de pan.','4 sesiones, 2 series por ejercicio, 3 repeticiones en reserva.','2 × 15 min suaves','Medí tu promedio habitual; no fuerces 10.000.','Peso 4–7 días, cintura y fotos iniciales.'],
['Hacerlo repetible','Organizá 2 tandas de cocina; proteína en 4 comidas. Mantené calorías.','Volumen completo si te recuperás; 2–3 repeticiones en reserva.','2 × 20 min','Base + 500 pasos/día si resulta cómodo.','Primera comparación de promedios; no recortes por el agua inicial.'],
['Encontrar tu ritmo','Revisá hambre, aceite y fines de semana. Ajustá solo con datos suficientes.','Sumá repeticiones antes de subir peso.','2 × 25 min','Base + 1000 pasos/día si te recuperás bien.','Revisión de 3 semanas: tendencia, cintura y rendimiento.'],
['Revisar, no acelerar','Sostené lo que funciona. No reduzcas calorías por calendario.','Mantené cargas; si hay fatiga, quitá 30–40 % de series.','2 × 25–30 min','Mantené pasos, sin saltos bruscos.','Día 30: cintura, fotos, promedios y fuerza.'],
['Consolidar','Rotá los tres menús y usá opciones económicas.','Retomá volumen sostenible; 2 repeticiones en reserva.','3 × 20–25 min','Base + 1500, solo si energía y articulaciones acompañan.','Revisá sueño, adherencia y hambre.'],
['Ajustar con evidencia','Si hay estancamiento real, cambiá una sola variable.','Buscá mantener carga y repeticiones.','3 × 25–30 min','Mantené o sumá 500; rango orientativo final 7000–10000.','No recortes si cintura baja o faltan registros.'],
['Proteger el rendimiento','Si la fatiga persiste, considerá 7 días a mantenimiento estimado y consulta.','Descarga opcional: 30–40 % menos series.','2–3 × 20–30 min suave','Mantené lo tolerable.','Revisá dos sesiones consecutivas con peor rendimiento.'],
['Preparar la continuidad','Practicá el patrón que puedas sostener después del día 60.','4 sesiones, sin pruebas de máximos.','Hasta 90–150 min/sem contando caminatas rápidas','No aumentes por obligación.','Compará promedios, cintura, fotos y fuerza.'],
['Días 57–60 · balance','Elegí el siguiente bloque con tus datos reales, no con una fecha límite.','Mantené rutina y buena técnica.','Cardio cómodo, sin compensaciones','Mantené tu promedio sostenible.','Día 60: revisión mensual y decisión del próximo bloque.']
];


