import {useEffect,useState,type ReactNode} from 'react';import type {Session} from '@supabase/supabase-js';import {client,configured,redirectURL,supabase} from '@/lib/supabase';
export function AuthGate({children}:{children:ReactNode}){const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(configured),[mode,setMode]=useState<'login'|'signup'|'reset'|'recovery'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
useEffect(()=>{if(!supabase)return;let alive=true;supabase.auth.getSession().then(({data,error})=>{if(!alive)return;setSession(data.session);setLoading(false);if(error)setMessage('No se pudo restaurar la sesión. Iniciá sesión otra vez.');});const {data}=supabase.auth.onAuthStateChange((event,s)=>{setSession(s);setLoading(false);if(event==='PASSWORD_RECOVERY')setMode('recovery');if(event==='SIGNED_OUT'){setMode('login');setPassword('');}});return()=>{alive=false;data.subscription.unsubscribe()}},[]);
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{if(mode==='reset'){const {error}=await client().auth.resetPasswordForEmail(email,{redirectTo:redirectURL()});if(error)throw error;setMessage('Si existe una cuenta con ese correo, recibirás un enlace para cambiar la contraseña.');}
else if(mode==='recovery'){const {error}=await client().auth.updateUser({password});if(error)throw error;setPassword('');setMode('login');setMessage('Contraseña actualizada.');}
else if(mode==='signup'){const {data,error}=await client().auth.signUp({email,password,options:{emailRedirectTo:redirectURL()}});if(error)throw error;if(!data.session)setMessage('Revisá tu correo y confirmá la cuenta antes de ingresar.');setPassword('');}
else{const {error}=await client().auth.signInWithPassword({email,password});if(error)throw error;setPassword('');}}
catch{setMessage(mode==='login'?'No pudimos ingresar. Revisá correo, contraseña y confirmación de cuenta.':'No se pudo completar. Revisá la conexión y reintentá en unos minutos.');}finally{setBusy(false)}}
if(loading)return <main className="authScreen"><div className="panel" role="status">Abriendo tu cuenta…</div></main>;
if(session&&mode!=='recovery')return <div key={session.user.id}><div className="accountBar"><span>{session.user.email}</span><span>Sincronización privada</span><button className="textButton" onClick={async()=>{const {error}=await client().auth.signOut();if(error)setMessage('No se pudo cerrar la sesión. Reintentá.');}}>Cerrar sesión</button>{message&&<span role="status">{message}</span>}</div>{children}</div>;
return <main className="authScreen"><div className="authBrand">F<span>60</span></div><section className="panel authPanel"><p className="eyebrow">FUERZA / 60</p><h1>{!configured?'Conectá tu aplicación.':mode==='signup'?'Tu progreso empieza acá.':mode==='recovery'?'Elegí una contraseña nueva.':'Tu plan, en todos tus dispositivos.'}</h1>{!configured?<><p>El diseño y el código están listos. Falta conectar el proyecto de Supabase para activar las cuentas, los registros y las fotos.</p><ol><li>Creá el proyecto y aplicá la migración incluida.</li><li>Configurá la URL y la clave publicable en GitHub.</li><li>Ejecutá el despliegue de GitHub Pages.</li></ol><p>La guía <b>README.md</b> del repositorio explica cada paso. No se simula un guardado mientras falta esta conexión.</p></>:<><p>Entrá con la misma cuenta en el celular y la computadora. Tus medidas y fotos solo serán accesibles desde tu cuenta.</p><form onSubmit={submit}>{mode!=='recovery'&&<label className="field">Correo electrónico<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label>}{mode!=='reset'&&<label className="field">Contraseña<input type="password" minLength={8} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} required/></label>}<button disabled={busy}>{busy?'Un momento…':mode==='signup'?'Crear mi cuenta':mode==='reset'?'Enviar enlace':mode==='recovery'?'Guardar contraseña':'Ingresar'}</button></form>{mode!=='recovery'&&<div className="authLinks"><button className="textButton" onClick={()=>{setMode(mode==='signup'?'login':'signup');setMessage('')}}>{mode==='signup'?'Ya tengo cuenta':'Crear una cuenta'}</button><button className="textButton" onClick={()=>{setMode(mode==='reset'?'login':'reset');setMessage('')}}>{mode==='reset'?'Volver a ingresar':'Olvidé mi contraseña'}</button></div>}<p className="caption">No compartas tu contraseña. En equipos compartidos, cerrá la sesión al terminar.</p></>}<p role="status">{message}</p></section></main>}
