"use client";
import {useEffect,useState,useRef} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Activity,Dumbbell,Utensils,CalendarDays,ChartNoAxesCombined,Check,Flame,Footprints,Download,Settings2} from 'lucide-react';
import {initialProfile,today,dayOf,offset,mean,review,menus,nutrition,foods,extra,sessions,weeks} from '@/lib/plan';
import {loadRecords,saveRecord,uploadPhoto,importBackup} from '@/lib/data';
import {recordKey} from '@/lib/validation';
import {PrivatePhoto} from '@/components/PrivatePhoto';
type Row=Record<string,any>;
const round=(n:number)=>Math.round(n).toLocaleString('es-AR');
function Choice({value,onChange,options,label}:{value:string,onChange:(v:string)=>void,options:string[][],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
function Field({label,name,value,onChange,min,max,step='1',type='number',required=false}:any){return <label className="field">{label}<input name={name} type={type} min={min} max={max} step={step} required={required} value={value??''} onChange={e=>onChange(type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/></label>}
function Panel({title,children,className=''}:any){return <section className={'panel '+className}>{title&&<h2>{title}</h2>}{children}</section>}
const blank=(date=today())=>({date,weight:null,waist:null,calories:null,protein:null,steps:null,sleep:null,energy:null,hunger:null,water:null,cardio:null,notes:''});
export default function Home(){
const editRevisions=useRef(new Map<string,number|undefined>());
const requestVersion=useRef(0),draftDirty=useRef(false),[loaded,setLoaded]=useState(false),[backup,setBackup]=useState<File|null>(null);

const [tab,setTab]=useState('hoy'),[records,setRecords]=useState<Row[]>([]),[profile,setProfile]=useState({...initialProfile}),[draft,setDraft]=useState({...initialProfile}),[log,setLog]=useState<Row>(blank()),[status,setStatus]=useState('Cargando tus registros…'),[busy,setBusy]=useState(false),[menu,setMenu]=useState('0'),[portion,setPortion]=useState('2000'),[session,setSession]=useState('0'),[exercise,setExercise]=useState('0'),[lift,setLift]=useState({date:today(),kg:0,reps:8,rir:2}),[reviewNotes,setReviewNotes]=useState(''),[photo,setPhoto]=useState<File|null>(null),[photoDate,setPhotoDate]=useState(today()),[shoppingDays,setShoppingDays]=useState(7);
async function refresh(){const request=++requestVersion.current;try{const rows=await loadRecords();if(request!==requestVersion.current)return null;setRecords(rows);const saved=rows.find(x=>x.key==='profile');if(saved){setProfile(saved as any);if(!draftDirty.current)setDraft(saved as any)}setLoaded(true);setStatus('Sincronizado · '+new Date().toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'}));return rows;}catch(e:any){setStatus(e.message||'No se pudo sincronizar. Tus cambios siguen en el formulario.');return null}}
useEffect(()=>{refresh();const onFocus=()=>{if(document.visibilityState==='visible')refresh()};window.addEventListener('focus',onFocus);window.addEventListener('online',onFocus);document.addEventListener('visibilitychange',onFocus);const timer=window.setInterval(onFocus,60000);return()=>{requestVersion.current++;window.removeEventListener('focus',onFocus);window.removeEventListener('online',onFocus);document.removeEventListener('visibilitychange',onFocus);clearInterval(timer)}},[]);
async function save(type:string,data:any){if(type==='profile'&&data.calories!==profile.calories)data={...data,lastAdjustment:today()};setBusy(true);setStatus('Guardando…');try{const key=recordKey({type,...data});const expected=data.revision??(editRevisions.current.has(key)?editRevisions.current.get(key):records.find(r=>r.key===key)?.revision);await saveRecord(type,data,expected);editRevisions.current.delete(key);if(type==='profile')draftDirty.current=false;const rows=await refresh();if(rows){if(type==='log'){const saved=rows.find(x=>x.key===key);if(saved)setLog(saved)}setStatus('Guardado y sincronizado')}else setStatus('Guardado en la nube; no se pudo actualizar la vista. Tocá Actualizar antes de seguir.');return true}catch(e:any){setStatus(e.message||'No se guardó. Reintentá.');return false}finally{setBusy(false)}}
async function restore(){if(!backup)return;setBusy(true);try{if(backup.size>10*1024*1024)throw Error('El respaldo debe ser menor de 10 MB.');const rows=await loadRecords();const n=await importBackup(JSON.parse(await backup.text()),rows);await refresh();setStatus(n+' registros importados.');setBackup(null)}catch(e:any){setStatus(e.message||'No se pudo importar este respaldo.')}finally{setBusy(false)}}
function beginEdit(type:string,data:any){const key=recordKey({type,...data});if(!editRevisions.current.has(key))editRevisions.current.set(key,records.find(r=>r.key===key)?.revision)}
function changeLift(next:any){beginEdit('workout',{...next,session:Number(session),exercise:sessions[Number(session)].ex[Number(exercise)][0]});setLift(next)}
function changeDraft(next:any){beginEdit('profile',next);draftDirty.current=true;setDraft(next)}
const logs=records.filter(x=>x.type==='log').sort((a,b)=>a.date.localeCompare(b.date)),lifts=records.filter(x=>x.type==='workout'),photos=records.filter(x=>x.type==='photo'),result=review(logs,profile),day=dayOf(profile.start),week=Math.max(0,Math.min(8,Math.floor((day-1)/7))),current=logs.filter(x=>x.weight!=null).at(-1)?.weight??profile.initialWeight??0;
const latest=logs.find(x=>x.date===today()),selected=menus[Number(menu)],mealItems=selected.flatMap(x=>x.items),total=nutrition(portion==='2600'?[...mealItems,...extra.items]:mealItems);
const planCalories=profile.calories;const base=10*(profile.initialWeight??0)+6.25*(profile.height??0)-5*(profile.age??0);const low=(base+(profile.sex==='male'?5:-161))*1.4,high=(base+(profile.sex==='female'?-161:5))*1.6;
const weekRows=Array.from({length:9},(_,i)=>{const a=offset(profile.start,i*7),b=offset(profile.start,Math.min(59,i*7+6));const rows=logs.filter(x=>x.date>=a&&x.date<=b);return {week:i+1,weight:mean(rows,'weight'),waist:mean(rows,'waist'),steps:mean(rows,'steps'),sleep:mean(rows,'sleep'),n:rows.filter(x=>x.weight!=null).length}});
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();try{Promise.resolve(ctx.registerTool({name:'read_progress_summary',title:'Leer resumen de progreso',description:'Lee los promedios y la revisión visibles; no modifica datos.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{if(!input||Object.keys(input).length)throw Error('No se admiten parámetros');return {day,calories:planCalories,...result}}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort()},[records,profile]);
function exportData(){const b=new Blob([JSON.stringify({format:'fuerza60',version:1,exportedAt:new Date().toISOString(),records},null,2)],{type:'application/json'});const url=URL.createObjectURL(b);const a=document.createElement('a');a.href=url;a.download='fuerza-60-registros.json';a.click();URL.revokeObjectURL(url)}
function selectDate(date:string){setLog(logs.find(x=>x.date===date)||blank(date))}
const stats=[[round(planCalories),'kcal · objetivo actual'],['180–210 g','proteína diaria'],['4 sesiones','fuerza por semana'],['0,4–0,9 kg','ritmo semanal orientativo']];
if(!loaded)return <main className="shell"><Panel title="Tus registros"><p role="status">{status}</p><button onClick={refresh}>Reintentar sincronización</button></Panel></main>;
if(!records.some(r=>r.key==='profile'))return <main className="shell"><Panel title="Configurá tu punto de partida"><p>Estos datos se guardan en tu cuenta, no en el código de GitHub. El plan alimentario incluido es un ejemplo orientado a una meta de 100 kg; revisá la ingesta con un profesional si tu situación es diferente.</p><form onSubmit={async e=>{e.preventDefault();await save('profile',draft)}}><div className="formGrid">{[['age','Edad (años)',18,90,1],['height','Altura (cm)',130,220,1],['initialWeight','Peso inicial (kg)',40,250,.1],['goalWeight','Meta de largo plazo (kg)',40,250,.1]].map(([key,label,min,max,step]:any)=><Field key={key} label={label} value={(draft as any)[key]} min={min} max={max} step={step} required onChange={(v:any)=>changeDraft({...draft,[key]:v})}/>)}</div><div className="formGrid">{[['age','Edad (años)',18,90,1],['height','Altura (cm)',130,220,1],['initialWeight','Peso inicial (kg)',40,250,.1],['goalWeight','Meta de largo plazo (kg)',40,250,.1]].map(([key,label,min,max,step]:any)=><Field key={key} label={label} value={(draft as any)[key]} min={min} max={max} step={step} required onChange={(v:any)=>changeDraft({...draft,[key]:v})}/>)}</div><Field label="Fecha de inicio" type="date" value={draft.start} required onChange={(v:string)=>changeDraft({...draft,start:v})}/><button disabled={busy}>Guardar y abrir mi plan</button></form><hr/><h3>O importar mi configuración o respaldo</h3><input aria-label="Archivo de respaldo" type="file" accept=".json,application/json" onChange={e=>setBackup(e.target.files?.[0]??null)}/><button disabled={busy||!backup} onClick={restore}>Importar archivo</button><p role="status">{status}</p></Panel></main>;
return <div className="shell"><header><a className="brand" href={import.meta.env.BASE_URL}>F<span>60</span><b>FUERZA / 60</b></a><span className="eyebrow">TU PLAN PERSONAL · 60 DÍAS</span><button className="subtle" onClick={()=>setTab('perfil')} aria-label="Configurar mi plan"><Settings2 size={18}/></button></header>
<Tabs value={tab} onValueChange={setTab}><TabsList className="nav">{[['hoy','Hoy',Activity],['comidas','Alimentación',Utensils],['fuerza','Fuerza',Dumbbell],['ruta','Hoja de ruta',CalendarDays],['progreso','Progreso',ChartNoAxesCombined],['perfil','Mi plan',Settings2]].map(([id,label,Icon]:any)=><TabsTrigger value={id} key={id}><Icon/>{label}</TabsTrigger>)}</TabsList>
<div className="sync" role="status">{status} <button onClick={refresh} className="textButton">Actualizar</button></div>
<TabsContent value="hoy"><div className="heading"><div><p className="eyebrow">CONSTANCIA ANTES QUE PERFECCIÓN</p><h1>Más fuerza.<br/><span>Menos grasa.</span></h1><p>{profile.age} años · {profile.height} cm · {profile.initialWeight} kg iniciales · 4 días de pesas</p></div><div className="stamp">{Math.max(0,Math.min(60,day))}<small>{day<1?'TU PLAN ESTÁ POR EMPEZAR':day>60?'BLOQUE COMPLETADO':'DE 60 DÍAS · SEMANA '+(week+1)}</small></div></div>
<div className="metrics">{stats.map(([n,l])=><article key={l}><small>{l}</small><strong>{n}</strong></article>)}</div>
<div className="grid"><Panel><div className="line"><p className="eyebrow">HOY CUENTA</p><span className="badge">{latest?'Día registrado':'Listo para empezar'}</span></div><h2>Una decisión a la vez</h2><div className="checkline"><Check/> Proteína en cada comida y verduras en dos.</div><div className="checkline"><Footprints/> Caminá según tu base, sin compensar con cardio.</div><div className="checkline"><Dumbbell/> Entrená con 2–3 repeticiones en reserva.</div><button onClick={()=>{selectDate(today());setTab('progreso')}}>Registrar mi día</button></Panel><Panel className="dark"><p className="eyebrow">TU PRÓXIMA REVISIÓN</p><h2>{result.title}</h2><p>{result.message}</p><button className="lime" onClick={()=>setTab('progreso')}>Ver mi tendencia</button></Panel></div>
<div className="grid lower"><Panel title="Tu progreso tiene contexto"><div className="line"><strong>{current} kg <small>último peso registrado{logs.length?'':' · inicial'}</small></strong><span>Meta: {profile.goalWeight} kg</span></div><Progress value={Math.max(0,Math.min(100,((profile.initialWeight??0)-current)/Math.max(1,(profile.initialWeight??0)-(profile.goalWeight??0))*100))} aria-label="Avance hacia la meta de largo plazo"/><p>{profile.goalWeight} kg es una meta de largo plazo. Un descenso orientativo de 3–7 kg en 60 días puede ser razonable, pero no está garantizado ni sería todo grasa.</p><p>Un peso aislado no decide el plan. Valoramos cintura, fuerza y bienestar.</p></Panel><Panel title={'Semana '+(week+1)+' · '+weeks[week][0]}><p>{weeks[week][1]}</p><p><b>Recuperación:</b> 7–9 horas de sueño y al menos 2 días sin pesas.</p><button className="subtle" onClick={()=>setTab('ruta')}>Abrir hoja de ruta</button></Panel></div></TabsContent>
<TabsContent value="comidas"><div className="sectionHead"><p className="eyebrow">COMER BIEN, SIN COMPLICARLO</p><h1>Tu mesa, tu plan.</h1><p>Verduras, legumbres y alimentos cotidianos. El pan puede tener su lugar.</p></div><div className="notice"><b>2000 kcal es el menú solicitado, no el inicio recomendado.</b> Tu mantenimiento provisional es de unas {round(Math.round(low/100)*100)}–{round(Math.round(high/100)*100)} kcal. Empezá alrededor de 2500–2800; el objetivo actual es {round(planCalories)}. Ajustá con 2–3 semanas de datos.</div>
<div className="toolbar"><Choice label="Menú" value={menu} onChange={setMenu} options={[['0','Menú base · lentejas y garbanzos'],['1','Alternativa 1 · porotos y papas'],['2','Alternativa 2 · garbanzos y atún']]}/><Choice label="Tamaño del menú" value={portion} onChange={setPortion} options={[['2000','Ejemplo de unas 2000 kcal'],['2600','Con complemento de unas 600 kcal']]}/></div>
<div className="metrics compact">{[[total[0],'kcal aproximadas'],[total[1],'g proteína'],[total[2],'g carbohidratos'],[total[3],'g grasas']].map(([n,l])=><article key={l}><small>{l}</small><strong>{round(Number(n))}</strong></article>)}</div><p className="caption">Cantidades por persona. Pesos comestibles y cocidos/escurridos, salvo avena seca; leche en ml, aceite en g. 100 g de huevo ≈ 2 huevos. Valores orientativos: etiquetas, cocción y marcas cambian el resultado; fibra y redondeo explican diferencias con 4/4/9.</p>
<div className="mealGrid">{selected.map((m,i)=>{const n=nutrition(m.items);return <Panel key={m.name}><div className="line"><span className="mealIndex">0{i+1}</span><span className="badge">{round(n[0])} kcal</span></div><h2>{m.name}</h2><ul className="ingredients">{m.items.map(([id,q])=><li key={id}><span>{foods[id][0]}</span><b>{q} {id==='leche'?'ml':'g'}</b></li>)}</ul><div className="macros">P {round(n[1])} g <span>C {round(n[2])} g</span><span>G {round(n[3])} g</span></div><p>{m.tip}</p></Panel>})}</div>
{portion==='2600'&&<Panel title={extra.name}><p>{extra.items.map(([id,q])=>q+' g '+foods[id][0]).join(' · ')}</p><p>{extra.tip} Aporta unas {round(nutrition(extra.items)[0])} kcal. Si tu objetivo cambió, ajustá porciones de arroz, pan o aceite sin quitar proteína.</p></Panel>}
<div className="grid"><Panel title="Antes y después de entrenar"><p><b>60–120 min antes:</b> yogur alto en proteína 200 g + banana 100 g: ≈209 kcal, 21 g P, 31 g C, 1 g G. Usalo como parte de la merienda.</p><p><b>Después, en las horas siguientes:</b> pollo cocido 120 g + arroz cocido 150 g: ≈393 kcal, 41 g P, 42 g C, 5 g G, como parte de almuerzo/cena. No hace falta una ventana de minutos.</p><p><b>Snacks alternativos:</b> yogur alto en proteína 200 g ≈120 kcal/20 g P; queso magro 100 g ≈160 kcal/24 g P; leche descremada 300 ml ≈105 kcal/10 g P. Reemplazan parte de una comida; no se suman sin contar.</p></Panel><Panel title="Saciedad, hidratación y presupuesto"><p>Buscá 25–35 g de fibra al día, subiendo poco a poco. Enjuagá legumbres en lata; remojá y cociná bien las secas.</p><p>Como inicio, 2–3 litros de bebidas al día y aproximadamente 400–800 ml por hora de ejercicio según calor y sudor. Ajustá por sed y orina amarillo claro; no fuerces grandes cantidades.</p><p>Comprá verduras de estación o congeladas, legumbres secas, huevos y pollo por oferta. Prepará 2–3 días y congelá el resto. Lácteos altos en proteína pueden variar de precio; compará costo por porción.</p><p>Pasá de frituras frecuentes a horno/plancha la mayoría de días. Medí aceite y serví el pan: una porción de 30–60 g puede entrar en tu plan.</p></Panel></div>
<Panel title="Lista de compras"><div className="toolbar"><Choice label="Días de compras" value={String(shoppingDays)} onChange={v=>setShoppingDays(Number(v))} options={[['3','Para 3 días'],['7','Para 7 días']]}/><p>Para repetir el menú seleccionado. Cambia junto con el menú y su complemento.</p></div><ul className="shopping">{Object.entries((portion==='2600'?[...mealItems,...extra.items]:mealItems).reduce((a:any,[id,q])=>({...a,[id]:(a[id]||0)+q*shoppingDays}),{})).map(([id,q]:any)=><li key={id}><b>{foods[id][0]}</b><span>{round(q)} {id==='leche'?'ml':'g'}</span></li>)}</ul><p className="caption">Cantidades cocidas: para comprar, pollo crudo ≈ peso cocido ÷ 0,75; legumbres secas ≈ cocidas ÷ 2,5; arroz seco ≈ cocido ÷ 3. El rendimiento varía. Agregá especias, limón y sal según necesidad.</p></Panel></TabsContent>
<TabsContent value="fuerza"><div className="sectionHead"><p className="eyebrow">ENTRENAR PARA CONSERVAR</p><h1>Fuerte, también en déficit.</h1><p>Torso / pierna · lunes, martes, jueves y viernes · 50–70 minutos.</p></div><div className="notice">Asume experiencia con pesas y ausencia de lesiones. Mucho peso solo si mantenés técnica: no hagas máximos ni llegues al fallo de forma habitual. Si un ejercicio duele, interrumpilo y usá una alternativa tolerable.</div>
<div className="toolbar"><Choice label="Sesión de entrenamiento" value={session} onChange={v=>{setSession(v);setExercise('0')}} options={sessions.map((s,i)=>[String(i),s.day+' · '+s.name])}/><span className="badge">2–3 repeticiones en reserva</span></div>
<Panel title={sessions[Number(session)].name}><p>Calentá 5–8 min caminando o pedaleando, movilizá las articulaciones que usarás y hacé 2–4 series de aproximación del primer ejercicio aumentando carga sin fatiga. Las series de calentamiento no cuentan.</p><div className="tableWrap"><Table><TableHeader><TableRow>{['Ejercicio','Series','Repeticiones','Descanso','Técnica / alternativa'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{sessions[Number(session)].ex.map(e=><TableRow key={e[0]}><TableCell><b>{e[0]}</b></TableCell><TableCell>{e[1]}</TableCell><TableCell>{e[2]}</TableCell><TableCell>{e[3]}</TableCell><TableCell>{e[4]}<small className="block">Alternativa: {e[5]}</small></TableCell></TableRow>)}</TableBody></Table></div></Panel>
<div className="grid"><Panel title="Progresión sin perseguir récords"><p>Semana 1: 2 series por ejercicio y 3 repeticiones en reserva (RIR). Desde semana 2, usá las series de la tabla si te recuperás bien.</p><p>Cuando completes el máximo del rango en todas las series con 2 RIR durante 2 sesiones, aumentá la carga mínima disponible (aprox. 2–5 %) y volvé al extremo inferior.</p><p>Mantener carga y repeticiones en déficit ya es progreso. Si caen más de 5–10 % durante 2 sesiones, revisá sueño, energía y déficit; quitá 30–40 % de series una semana.</p></Panel><Panel title="Cardio que acompañe"><p>Miércoles y sábado: caminata rápida, bici o elíptica. Intensidad de conversación: podés hablar en frases completas.</p><p>Empezá con 2 × 15–20 min y progresá hacia 90–150 min semanales, contando caminatas rápidas, si recuperás bien. Después de las pesas o separado varias horas; no hace falta HIIT.</p><p>Domingo: descanso o paseo suave. Aumentá pasos de a 500–1000, según tu base y tolerancia.</p></Panel></div>
<Panel title="Registro de tu serie de referencia"><p>Guardá la primera serie efectiva del ejercicio, con la misma técnica y RIR. Compará repeticiones a igual carga; las máquinas distintas no son comparables.</p><form onSubmit={async e=>{e.preventDefault();await save('workout',{...lift,session:Number(session),exercise:sessions[Number(session)].ex[Number(exercise)][0]})}}><div className="formGrid"><Field label="Fecha" type="date" value={lift.date} required onChange={(v:string)=>changeLift({...lift,date:v})}/><label className="field">Ejercicio<Choice label="Ejercicio de referencia" value={exercise} onChange={setExercise} options={sessions[Number(session)].ex.map((e,i)=>[String(i),e[0]])}/></label><Field label="Carga total (kg)" value={lift.kg} min={0} max={600} step=".5" required onChange={(v:number)=>changeLift({...lift,kg:v})}/><Field label="Repeticiones" value={lift.reps} min={1} max={50} required onChange={(v:number)=>changeLift({...lift,reps:v})}/><Field label="RIR · repeticiones en reserva" value={lift.rir} min={0} max={10} required onChange={(v:number)=>changeLift({...lift,rir:v})}/></div><p className="caption">Mancuernas: anotá siempre la suma de ambas; peso corporal: registrá 0 kg de carga externa.</p><button disabled={busy}>Guardar serie</button></form>
<div className="history">{lifts.filter(x=>x.exercise===sessions[Number(session)].ex[Number(exercise)][0]).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8).map(x=><div key={x.key}>{x.date} · <b>{x.kg} kg × {x.reps}</b> · RIR {x.rir}</div>)}</div></Panel></TabsContent>
<TabsContent value="ruta"><div className="sectionHead"><p className="eyebrow">OCHO SEMANAS + CUATRO DÍAS</p><h1>Un camino sostenible.</h1><p>Las semanas guían hábitos. Tus resultados deciden los ajustes.</p></div><div className="notice">En todas las semanas: objetivo actual {round(planCalories)} kcal, 180–210 g de proteína, sueño 7–9 h y revisión cada 7 días. No hay una cuota obligatoria de kilos por semana.</div><div className="timeline">{weeks.map((w,i)=><Panel key={w[0]} className={i===week?'activeWeek':''}><div className="line"><p className="eyebrow">{i===8?'DÍAS 57–60':'SEMANA '+(i+1)+' · DÍAS '+(i*7+1)+'–'+(i*7+7)}</p>{i===week&&<span className="badge">Tu etapa actual</span>}</div><h2>{w[0]}</h2><div className="routeGrid">{['Alimentación','Fuerza','Cardio','Pasos','Revisión'].map((l,j)=><div key={l}><b>{l}</b><p>{w[j+1]}</p></div>)}</div></Panel>)}</div><Panel title="Revisiones de los días 30 y 60"><p>Compará la media de los últimos 7 días con la inicial, cintura tomada igual, fotos y series de referencia. Anotá qué hábitos fueron fáciles, qué te hizo pasar hambre y qué podés sostener. El éxito incluye cintura menor, fuerza estable y mejor adherencia, incluso si la balanza va más lenta.</p><p>Si necesitás más tiempo para llegar a {profile.goalWeight} kg, continuá en bloques. No aceleres las últimas semanas para cumplir una fecha.</p></Panel></TabsContent>
<TabsContent value="progreso"><div className="sectionHead"><p className="eyebrow">DATOS REALES, DECISIONES TRANQUILAS</p><h1>La tendencia importa.</h1><p>Registrá sin juzgar. No hacen falta días perfectos.</p></div><div className="metrics compact">{[[result.current?.toFixed(1)??'—','kg · media últimos 7 días'],[result.loss===null?'—':result.loss.toFixed(2),'kg · descenso vs. semana anterior'],[Math.round(result.adherence*100)+'%','adherencia · últimos 7 días'],[logs.length,'días registrados']].map(([n,l])=><article key={l}><small>{l}</small><strong>{n}</strong></article>)}</div>
<div className="grid"><Panel title="Registrar un día"><form onSubmit={async e=>{e.preventDefault();await save('log',log)}}><div className="formGrid"><Field label="Fecha" type="date" value={log.date} required onChange={selectDate}/>{[['weight','Peso (kg)',40,250,.1],['waist','Cintura (cm)',40,200,.1],['calories','Calorías consumidas',0,8000,1],['protein','Proteína (g)',0,400,1],['steps','Pasos',0,60000,1],['sleep','Sueño (h)',0,16,.25],['energy','Energía (1 baja–5 alta)',1,5,1],['hunger','Hambre (1 baja–5 alta)',1,5,1],['water','Bebidas (litros)',0,10,.1],['cardio','Cardio moderado (min)',0,240,1]].map(([key,label,min,max,step]:any)=><Field key={key} label={label} value={log[key]} min={min} max={max} step={step} onChange={(v:any)=>{beginEdit('log',log);setLog({...log,[key]:v})}}/>)}</div><label className="field">Notas · entrenamiento, sal, ciclo, estrés<textarea maxLength={2000} value={log.notes} onChange={e=>{beginEdit('log',log);setLog({...log,notes:e.target.value})}}/></label><p className="caption">Dejá vacío lo que no mediste. Guardar otra vez la misma fecha actualiza ese día.</p><button disabled={busy}>Guardar registro</button></form></Panel>
<div><Panel title={result.title} className="reviewPanel"><p>{result.message}</p><p className="caption">La revisión se recalcula al abrir o actualizar la aplicación. No es un entrenador que vigile tus datos en segundo plano.</p>{result.delta!==0&&<button disabled={busy} onClick={()=>save('profile',{...profile,calories:Math.min(3500,Math.max(2000,profile.calories+result.delta))})}>Aplicar {result.delta>0?'+':''}{result.delta} kcal al objetivo</button>}<p className="caption">La adherencia cuenta días con calorías dentro de ±150 del objetivo actual y ≥180 g de proteína; faltantes cuentan como desconocidos/no cumplidos. Si cambiaste el objetivo esta semana, interpretá el porcentaje con cautela.</p></Panel><Panel title="Tu revisión semanal"><ol><li>¿La media baja y la cintura acompaña?</li><li>¿Mantuve cargas, repeticiones y técnica?</li><li>¿Cuántos días seguí realmente la alimentación?</li><li>¿Tengo hambre tolerable y energía suficiente?</li><li>¿Dormí 7–9 h y mantuve pasos constantes?</li><li>¿Qué único cambio haré esta semana?</li></ol><textarea aria-label="Notas de revisión semanal" maxLength={4000} value={reviewNotes} onChange={e=>{beginEdit('review',{date:today()});setReviewNotes(e.target.value)}} placeholder="Mis resultados y mi decisión para esta semana…"/><button disabled={busy||!reviewNotes.trim()} onClick={()=>save('review',{date:today(),notes:reviewNotes,calories:planCalories})}>Guardar revisión</button></Panel></div></div>
<Panel title="Evolución semanal"><div className="trendBars" role="img" aria-label="Medias de peso por semana; las barras se expresan desde cero">{weekRows.map(r=><div key={r.week}><span>{r.weight===null?'—':r.weight.toFixed(1)}</span><div style={{height:r.weight===null?4:Math.max(4,r.weight/150*130)}}/><small>S{r.week}</small></div>)}</div><div className="tableWrap"><Table><TableHeader><TableRow>{['Semana','Peso medio','N.º de pesos','Cintura media','Pasos medios','Sueño medio'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{weekRows.map(r=><TableRow key={r.week}><TableCell>{r.week}</TableCell><TableCell>{r.weight?.toFixed(1)??'—'} kg</TableCell><TableCell>{r.n}{r.n>0&&r.n<4?' · pocos datos':''}</TableCell><TableCell>{r.waist?.toFixed(1)??'—'} cm</TableCell><TableCell>{r.steps===null?'—':round(r.steps)}</TableCell><TableCell>{r.sleep?.toFixed(1)??'—'} h</TableCell></TableRow>)}</TableBody></Table></div></Panel>
<div className="grid"><Panel title="Grasa o agua: cómo distinguirlas"><p>Pesate 4–7 mañanas por semana, después de ir al baño y antes de comer, con la misma balanza y ropa similar. Si pesarte a diario te genera malestar, usá menos mediciones y tendencias más largas.</p><p>Sal, carbohidratos, estreñimiento, entrenamiento intenso, creatina y ciclo menstrual pueden mover 1–3 kg sin reflejar grasa. Una bajada grande inicial suele incluir agua y glucógeno.</p><p>Una media menor durante 2–4 semanas y cintura que baja apoyan la idea de pérdida de grasa; no permiten medirla exactamente. Compará fases equivalentes del ciclo si corresponde.</p><p>Cintura: 1 vez por semana al nivel del ombligo, al final de una espiración normal, sin apretar; hacé 2 medidas. Fotos cada 2 semanas, misma luz, distancia, ropa y postura.</p></Panel><Panel title="Fotos de progreso · tu cuenta"><p>Guardá una foto o collage frontal/lateral por fecha. Se guarda en tu cuenta; otras cuentas no pueden verla. JPG, PNG o WebP, hasta 5 MB.</p><form onSubmit={async e=>{e.preventDefault();if(!photo)return;setBusy(true);try{const expected=editRevisions.current.get('photo:'+photoDate);await uploadPhoto(photo,photoDate,expected);editRevisions.current.delete('photo:'+photoDate);setPhoto(null);const rows=await refresh();setStatus(rows?'Foto guardada y sincronizada':'Foto guardada; actualizá la vista antes de continuar.')}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}}><Field label="Fecha de la foto" type="date" value={photoDate} required onChange={(v:string)=>{setPhotoDate(v);setPhoto(null)}}/><input aria-label="Elegir foto" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{beginEdit('photo',{date:photoDate});setPhoto(e.target.files?.[0]??null)}}/><button disabled={busy||!photo}>Guardar foto</button></form><div className="photos">{photos.sort((a,b)=>a.date.localeCompare(b.date)).map(p=><PrivatePhoto key={p.key+String(p.revision)} path={p.path} date={p.date}/>)}</div></Panel></div>
<Panel title="Historial y respaldo"><button className="subtle" onClick={exportData}><Download size={16}/> Descargar mis registros</button><p className="caption">El respaldo JSON contiene tu configuración, medidas, series y revisiones. Las fotos se descargan por separado abriéndolas. Guardá tus copias fuera de GitHub.</p><details><summary>Importar un respaldo</summary><p>Solo agrega registros nuevos. Si hay fechas o configuración ya existentes, cancela la importación completa para evitar sobrescrituras. Las fotos no se importan desde JSON.</p><input aria-label="Archivo de respaldo" type="file" accept=".json,application/json" onChange={e=>setBackup(e.target.files?.[0]??null)}/><button disabled={busy||!backup} onClick={restore}>Importar registros nuevos</button></details><div className="history">{records.filter(x=>x.type==='review').sort((a,b)=>b.date.localeCompare(a.date)).map(r=><details key={r.key}><summary>{r.date} · revisión · {r.calories} kcal</summary><p>{r.notes}</p></details>)}</div><details><summary>Ver y editar registros diarios ({logs.length})</summary>{[...logs].reverse().map(r=><div className="historyRow" key={r.key}><span>{r.date} · {r.weight??'—'} kg · {r.calories??'—'} kcal</span><button className="textButton" onClick={()=>{setLog(r);window.scrollTo({top:200,behavior:'smooth'})}}>Editar</button></div>)}</details></Panel></TabsContent>
<TabsContent value="perfil"><div className="sectionHead"><p className="eyebrow">EL PLAN SE ADAPTA A VOS</p><h1>Tu punto de partida.</h1><p>{profile.initialWeight} kg · {profile.height} cm · {profile.age} años · objetivo de largo plazo: {profile.goalWeight} kg.</p></div><div className="grid"><Panel title="Configurar mi plan"><form onSubmit={async e=>{e.preventDefault();await save('profile',draft)}}><div className="formGrid"><Field label="Fecha de inicio" type="date" value={draft.start} required onChange={(v:string)=>changeDraft({...draft,start:v})}/><Field label="Objetivo energético (kcal)" value={draft.calories} min={2000} max={3500} step={50} required onChange={(v:number)=>changeDraft({...draft,calories:v})}/><Field label="Pasos habituales antes del plan" value={draft.baselineSteps} min={1000} max={25000} step={100} required onChange={(v:number)=>changeDraft({...draft,baselineSteps:v})}/><label className="field">Sexo usado por la ecuación<Choice label="Sexo de la fórmula" value={draft.sex} onChange={v=>changeDraft({...draft,sex:v})} options={[['unknown','Sin especificar · mostrar rango'],['male','Masculino'],['female','Femenino']]}/></label></div><label className="field">Lesiones, condiciones, medicación, alergias o preferencias<textarea value={draft.notes} maxLength={2000} onChange={e=>changeDraft({...draft,notes:e.target.value})}/></label><p className="caption">Estas notas se guardan para tus revisiones; no adaptan clínicamente el menú ni descartan alergias. El plan incluye lácteos, huevos, pollo y pescado.</p><button disabled={busy}>Guardar configuración</button></form></Panel><Panel title="Calorías sin falsa precisión"><p>Mifflin–St Jeor: 10 × peso + 6,25 × altura − 5 × edad + constante (5 o −161). Con tus datos, reposo ≈{round(base-161)}–{round(base+5)} kcal/día antes de precisar el sexo usado por la fórmula.</p><p>Con un factor orientativo 1,4–1,6, mantenimiento ≈{round(Math.round(low/100)*100)}–{round(Math.round(high/100)*100)} kcal/día. Cuatro sesiones de gimnasio no revelan cuánto te movés el resto del día.</p><p>Inicio provisional: 2500–2800 kcal; 2600 es un ensayo razonable, no una medición de tu gasto. Buscá aproximadamente 300–600 kcal de déficit y comprobalo con tendencias.</p><p>A {planCalories} kcal: proteína 180–210 g, grasa orientativa 65–85 g (aprox. 45–65 g en el ejemplo de 2000 kcal), carbohidratos como resto. Ejemplo coherente: 190 g P + 75 g G + {round((planCalories-190*4-75*9)/4)} g C ≈ {planCalories} kcal. No uses todos los extremos del rango a la vez.</p></Panel></div>
<Panel title="Reglas de ajuste"><ol><li>No modifiques calorías por un pesaje. Compará medias de 7 días con al menos 4 pesos por semana.</li><li>Si bajás 0,4–0,9 kg/sem, la cintura mejora y rendís bien, mantené.</li><li>Si durante 2 semanas el descenso es &lt;0,25 kg/sem y cintura estable, con adherencia ≥80 %, reducí 100–150 kcal O sumá 1000 pasos. No ambas cosas. Esperá 14 días.</li><li>Si bajás &gt;1 % del peso por semana después de la fase inicial o empeora la recuperación, considerá sumar 150–200 kcal y reducir volumen.</li><li>Si hay fatiga persistente, hambre intensa o pérdida de fuerza, no sigas recortando. Revisá el plan con un profesional.</li></ol></Panel>
<Panel title="Salud y límites del plan"><p>Es una guía educativa general, no una prescripción médica. Antes de aplicar el déficit, consultá si tenés enfermedad renal, diabetes tratada con medicación, antecedentes de trastornos alimentarios, embarazo/lactancia o restricciones de líquidos. En esos casos proteína e hidratación necesitan individualización.</p><p>Dolor de pecho, desmayo o falta de aire inusual: detené el ejercicio y buscá atención. Dolor articular persistente requiere evaluar técnica y carga. Evitá deshidratación, quemadores y compensar comidas con ejercicio.</p><p>El objetivo es proteger masa muscular; no se puede garantizar cuánto músculo o grasa cambia solo con una balanza.</p></Panel><Panel title="Fuentes y criterios"><p>Las cifras del menú son estimaciones de alimentos genéricos. El plan usa principios de pérdida gradual, proteína suficiente, entrenamiento de fuerza y recuperación.</p><ul className="sources"><li><a href="https://www.cdc.gov/healthy-weight-growth/losing-weight/index.html" target="_blank" rel="noreferrer">CDC · pérdida de peso gradual</a></li><li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC5477153/" target="_blank" rel="noreferrer">ISSN · proteína y ejercicio (2017)</a></li><li><a href="https://www.niddk.nih.gov/health-information/weight-management/body-weight-planner" target="_blank" rel="noreferrer">NIDDK · estimación y evolución del peso</a></li><li><a href="https://www.acsm.org/docs/default-source/files-for-resource-library/resistance-training-for-health.pdf" target="_blank" rel="noreferrer">ACSM · entrenamiento de fuerza</a></li><li><a href="https://www.cdc.gov/sleep/about/" target="_blank" rel="noreferrer">CDC · sueño en adultos</a></li></ul></Panel></TabsContent></Tabs><footer>FUERZA / 60 <span>Progreso sostenible. Datos reales. Sin atajos.</span></footer></div>}


